display_name: Sweep
package_name: sweep
maintainer:
  name: Abdulrasol
  email: rasol@example.com
priority: optional
section: utils
description: |
  Master Maintenance Suite for Developers.
  Clean build artifacts and reclaim storage.
